### ISSUE TITLE
validateOnMount does not validate field on first mount

### ISSUE THREAD

**Issue by psaruks** [formium/formik#2652] opened 2020-07-28 09:28 UTC
### Current Behavior

at first mount field has 0 errors with defined "initialValue" and "validateOnMount" flag

### Expected behavior

at the first mount, the validation field must have an error.

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-723xp

### Additional context

at **formik@2.1.3** all works fine.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.5
| React            | 16.11.0

**Comment by dhallstr** [comment] 2020-07-28 18:45
Looks like this works in 2.1.4 as well. I believe my PR #2625 will fix this.

**Comment by Raden-Hor** [comment] 2020-08-13 09:30
same issue on 2.1.5

**Comment by Aerophite** [comment] 2020-08-20 15:38
Any update on this? I'd like to be able to update Formik to keep my dependencies up to date but this issue is stopping me.

**Comment by DmitryIvanovIAMM** [comment] 2020-08-29 15:50
In the last version the property isInitialValid is marked as deprecated, but this was only way to disable submit button on initial empty form. Current initialErrors with validation schema makes the form valid on start even if it invalid (empty).

**Comment by b3coded** [comment] 2020-09-02 11:41
for now I'm using like this:

```js

import React, { useRef, useEffect } from 'react'
import {
  Formik as BaseFormik,
  Form as BaseForm,
  FormikProps,
  FormikConfig,
} from 'formik'

function Formik<Values>(props: FormikConfig<Values>) {
  const { children, ...rest } = props
  const formRef = useRef<FormikProps<Values> | null>(null)

  useEffect(() => {
    if (formRef.current) {
      formRef.current.validateForm()
    }
  }, [])

  return (
    <BaseFormik innerRef={formRef} {...rest}>
      <BaseForm>{children}</BaseForm>
    </BaseFormik>
  )
}

// Workaround for: https://github.com/formium/formik/issues/2652
export default Formik

```

So instead of import from `formik` I'm using this component

**Comment by cduff** [comment] 2020-09-30 05:40
Appears to be fixed in 2.1.6?

**Comment by Aerophite** [comment] 2020-09-30 22:07
@cduff 

Yes, I can confirm that it is fixed in 2.1.6.

**Closed** 2020-09-30 22:10 UTC

**Comment by ronenmagid** [comment] 2020-10-20 22:50
Yep. **CONFIRMED TOO** -- The bug is present in 2.1.5, but **fixed in 2.1.6** -- I just upgraded and tried it.

**Comment by peraltafederico** [comment] 2020-10-29 03:45
Yeap, confirm. It's working in 2.1.6

**Comment by Emiliano-Bucci** [comment] 2022-05-05 09:12
Hi! Could be this broken again, in `2.2.9`?

**Comment by malbaugh** [comment] 2022-06-01 15:07
I am also having issues in `2.2.9`

**Comment by mcrstudio** [comment] 2022-06-20 10:45
2.2.9 issues here for mount validation.

**Comment by peter-coastpay-com** [comment] 2022-07-12 15:40
having issues with 2.2.9

**Comment by oliviercperrier** [comment] 2022-08-02 19:20
Same here not working in 2.2.9

**Comment by Digital-Coder** [comment] 2022-08-09 13:22
in 2.2.9 validateOnMount caused me infinite rerenders

**Comment by TamirCode** [comment] 2022-09-21 07:00
2.2.9 `validateOnMount : true` only worked in my first project, but doesn't work in my new project (same formik versions)

my first project is typescript and my second isn't, maybe that could help

**Comment by MouraVocal** [comment] 2022-09-21 18:47
Documentations tells that only "touched" inputs will be validated, it would be nice if we have the option to validate without touching too.

**Comment by AzD3v** [comment] 2022-09-22 09:39
I'm suffering from the same issue.

I also have field styles that depend on a field being touched or not. I'm trying to come up with a solution that makes it possible for a field to be initially marked as touched (so it can be validated) but avoids marking the field as touched if the validation returns an error.

The workaround I found involves finding all initial errors using formik's `innerRef` and then add a condition on `initialTouched` prop to check if a given field returned a validation error (and so mark the field as touched) but it's just not clean.

**Comment by leonardomorenozaga** [comment] 2022-10-11 14:29
I had a similar situation, a form receiving initial values I need to kick validations with (here in case somebody finds it useful):

```
import { Formik, setNestedObjectValues } from 'formik';
const formikRef = useRef(null);

useEffect(() => {
     formikRef.current.validateForm().then(() =>
          formikRef.current.setTouched( // set the touched state once validateForm is done
             setNestedObjectValues(formikRef.current.errors, true),
          )
     );
}, []);
    

<Formik
      initialValues={customerData}
      innerRef={formikRef}
      ....
```

**Comment by rwb196884** [comment] 2023-07-16 05:38
Fixed code
```
  const formikRef: MutableRefObject<FormikProps<FormModelType> | null> = useRef<FormikProps<FormModelType> | null>(null);
  useEffect(() => {
    if (formikRef === null) {
      console.log('formikRef is null');
      return;
    }
    if (formikRef.current === null) {
      console.log('formikRef is null');
      return;
    }
    formikRef!.current!.validateForm().then(() =>
      formikRef!.current!.setTouched( // set the touched state once validateForm is done
        setNestedObjectValues(formikRef!.current!.errors, true),
      )
    );
  }, []);
```
and
```
innerRef={(f) => (formikRef.current = f)}
```
but the bastard piee of shit still doesn't validate intially.
