### ISSUE TITLE
Field as component type infer

### ISSUE THREAD

**Issue by JanKaczmarkiewicz** [formium/formik#3073] opened 2021-03-01 21:42 UTC
### Current Behavior

When `Field` is used with `as` component prop it can't inter props that passed component have.

### Desired Behavior

If  `Field` is used with `as` component prop it should inherit all props from it (Omit name, onChange, value etc). 

### Suggested Solution
I think that this can be something like:
```
export function Field<A extends string | React.ElementType>(
    props: GenericFieldHTMLAttributes &
      FieldConfig<any> & {
        name: string;
        as?: A;
      } & (A extends React.ElementType<infer P> ? P : {})
  ): any;
```

### Who does this impact? Who is this for?

It will impact typescript usage. I hope this feature will improve the usage of this brilliant library <3

**Comment by johnrom** [comment] 2021-03-01 21:43
You can see a pretty thorough but outdated approach here #1334

**Comment by johnrom** [comment] 2021-03-01 21:44
Closing as duplicate of #1334

**Closed by johnrom** 2021-03-01 21:44 UTC
Labels: Type: Feature Request
