### ISSUE TITLE
Pass native event to onSubmit handler

### ISSUE THREAD

**Issue by lkostrowski** [formium/formik#2838] opened 2020-10-26 08:50 UTC
### Current Behavior

Formik exposes values and formik helpers to the handler, but SubmitEvent stays hidden

### Desired Behavior

onSubmit exposes submit event

### Suggested Solution

3rd argument of handler can be `event: SubmitEvent`

or 

formik helpers get expose `getSubmitEvent` method

### Who does this impact? Who is this for?

Some forms are having 2 or more submit buttons.

Imagine form editing some entity with 2 buttons `[Save] [Save & Submit]`.

Currently its hard to do the workaround, because there is no easy information (or is it?) what button was triggered. It can be somehow bypassed by hidden checkboxes or manual event handling like this

```
onClick={(e) => {
							e.preventDefault();

							submitForm().then(() => {
								submitCallbackProp(values);
							});
						}}
```

but this is not an elegant solution

**Comment by johnrom** [comment] 2020-10-26 14:49
This is a duplicate of #1792

**Closed** 2020-10-28 19:41 UTC
Labels: Resolution: Duplicate
