### ISSUE TITLE
Typescript: standalone return type for useFormik

### ISSUE THREAD

**Issue by ialexi-bl** [formium/formik#2966] opened 2020-12-16 09:38 UTC
## Feature request

Currently `useEffect` is typed to return an anonymous object, not an interface or a type alias. This makes it very awkward in situation where it could be necessary to pass `formik` instance to some function or child component or whatever. This may not be intended but moving `useFormik` return type to a separate interface that can be used independently is a nice convenience that doesn't break anything. 

### Suggested Solution

Change

```ts
function useFormik<...>(...): {
  // ...
}
```

to

```ts
// Come up with a good name
interface FormikHookReturnType<...> = {
  // ...
}

function useFormik<...>(...): FormikHookReturnType<...>;
```

### Who does this impact? Who is this for?

Typescript users, no impact on existing code.

**Comment by apieceofbart** [comment] 2021-01-04 18:12
This is a duplicate of https://github.com/formium/formik/issues/2924

**Closed** 2021-01-05 04:15 UTC
Labels: Type: Feature Request
