### ISSUE TITLE
Yup required validation message not cleared even react-dates have value in it. (When using formik latest version)

### ISSUE THREAD

**Issue by puru0019** [formium/formik#2482] opened 2020-05-20 14:54 UTC
### Current Behavior

Yup required validation message is not getting cleared even if the date picker is having value inside it. The validation message is getting cleared when you focus in and focus out for the second time or change the date for second time

**Note: This issue was not present in formik v1.5.4**

### Expected behavior

Required validation message should get cleared as when value is present

### Reproducible example

https://codesandbox.io/s/formik-with-react-dates-9ztcz?file=/public/src/index.js

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.4
| React            | 16.13.0
| TypeScript       |
| Browser          |
| npm/Yarn         |
| Operating System | windows 10
| react-dates | 21.8.0

**Comment by johnrom** [comment] 2020-05-20 15:20
You're hitting a duplicate of #2457.

You can solve this by wrapping your `setFieldTouched` in a very quick setTimeout.

**Comment by puru0019** [comment] 2020-05-21 04:53
> You're hitting a duplicate of #2457.
> 
> You can solve this by wrapping your `setFieldTouched` in a very quick `setTimeout`.

Thank you @johnrom for the quick response. `setTimeout` is working for now. Is this the issue from formik? If so Will this get fixed in upcoming version of formik?

**Comment by maddhruv** [comment] 2020-11-07 04:10
Closing as resolved and duplicate

**Closed by maddhruv** 2020-11-07 04:10 UTC
Labels: Resolution: Duplicate
